AWSTemplateFormatVersion: '2010-09-09'
Description: Non-critical parts like codedeploy, alerts, etc.
Parameters:
  AsgGroup:
    Type: String
    Description: Autoscaling group from app stack
Resources:
  DeployRole: #create codedeploy role
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
               - codedeploy.us-east-2.amazonaws.com
               - codedeploy.us-east-1.amazonaws.com
               - codedeploy.us-west-1.amazonaws.com
               - codedeploy.us-west-2.amazonaws.com
               - codedeploy.eu-west-3.amazonaws.com
               - codedeploy.ca-central-1.amazonaws.com
               - codedeploy.eu-west-1.amazonaws.com
               - codedeploy.eu-west-2.amazonaws.com
               - codedeploy.eu-central-1.amazonaws.com
               - codedeploy.ap-northeast-1.amazonaws.com
               - codedeploy.ap-northeast-2.amazonaws.com
               - codedeploy.ap-southeast-1.amazonaws.com
               - codedeploy.ap-southeast-2.amazonaws.com
               - codedeploy.ap-south-1.amazonaws.com
               - codedeploy.sa-east-1.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
  CodeDeploy:
    Type: AWS::CodeDeploy::Application
    Properties:
      ComputePlatform: Server
  DeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      ApplicationName: !Ref CodeDeploy
      AutoScalingGroups:
        - !Ref AsgGroup
      DeploymentConfigName: CodeDeployDefault.OneAtATime
      DeploymentStyle: AutoScalingGroups
      ServiceRoleArn: !Ref DeployRole
  SpendingAlarm: #prevent things breaking the bank
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: "Alarm if spending is over 50USD this month"
      Namespace: AWS/Billing
      MetricName: EstimatedCharges
      Dimensions:
        - Name: Currency
          Value: USD
      Statistic: Maximum
      Period: '21600'
      EvaluationPeriods: '1'
      Threshold: 50
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref AlarmTopic
      InsufficientDataActions:
        - !Ref AlarmTopic
  AlarmTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: "sjoerdsantema@gmail.com"
          Protocol: 'email'
